name: Setup Python
runs:
  using: composite
  steps:
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install Python Requirements
      run: |
        pip install -r requirements.txt
      shell: bash
