name: Deploy

permissions:
  id-token: write
  contents: read

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

concurrency:
  group: deploy-${{ inputs.environment }}
  cancel-in-progress: false

jobs:
  deploy-pulumi:
    uses: ./.github/workflows/publish_package.yaml
    secrets: inherit
    with:
      environment: ${{ inputs.environment }}
