name: Lint

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Branch
        uses: actions/checkout@v3

      - name: Setup Python
        uses: ./.github/actions/setup-python

      - name: Lint
        run: flake8 . --show-source --statistics
